### ISSUE TITLE
System cannot find command btrview when running as sudo

### ISSUE THREAD

**Issue by watson-e-and** [CopOnTheRun/btrview#6]
I'm having trouble getting started. 

My OS is Fedora 39 (KDE spin), and I installed using `pip install btrview`.  When I try running `sudo btrview`, I get the error `sudo: btrview: command not found`. However, when I run just `btrview`, I get something that suggests that I do in fact have this command on my computer. 
```
$ btrview
WARNING: You're current running this script as user erin.
If you have problems, try rerunning this script with sudo, or as the root user.
Traceback (most recent call last):
  File "/home/erin/.local/bin/btrview", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/scripts/btrview.py", line 58, in main
    output = logic(args.labels, args.exclude, args.property, 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/rich_output.py", line 140, in logic
    subvols = fs.subvolumes(remove)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/btrfs.py", line 120, in subvolumes
    subvols = [] if "root" in remove else [Subvolume.from_ID("5",mount_point, self.mounts)]
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/subvolume.py", line 104, in from_ID
    props = cls._run_cmd(cmd)
            ^^^^^^^^^^^^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/subvolume.py", line 122, in _run_cmd
    out = run(cmd)
          ^^^^^^^^
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/utils.py", line 23, in run
    raise e
  File "/home/erin/.local/lib/python3.12/site-packages/btrview/utils.py", line 20, in run
    out = subprocess.run(tokens, check=True, capture_output=True, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['btrfs', 'subvolume', 'show', '-r', '5', '/home']' returned non-zero exit status 1.
```

Was there an installation step that I missed?

**Comment by CopOnTheRun** [comment]
I'm guessing this is an issue because the `$PATH` variable (basically a list of which programs you can execute) is different between running as a regular user and running with sudo on fedora. There's some trouble shooting steps listed in [this stackoverflow thread](https://stackoverflow.com/questions/12996397/command-not-found-when-using-sudo).

The top answer of that thread is probably the easiest `sudo -E env "PATH=$PATH" <command> [arguments]` for a quick fix, but something more permanent would be to edit the `secure_path` in your sudoers file. Unfortunately I'm not running a machine with fedora on it at the moment so I can't test these solutions myself.

**Comment by CopOnTheRun** [comment]
I've updated the README with some new installation instructions, check them out, I think it should fix your issues!
